name: korcourses
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  http: 1.2.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  responsive_builder: ^0.4.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/


  fonts:
    - family: Open-Sans
      fonts:
       - asset: assets/fonts/OpenSans-Bold.ttf
       - asset: assets/fonts/OpenSans-Italic.ttf
       - asset: assets/fonts/OpenSans-Light.ttf
       - asset: assets/fonts/OpenSans-Regular.ttf

    #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
